version: 0.2
env:
  git-credential-helper: yes
phases:
  pre_build:
    commands:
      - git submodule update --init --recursive
      - export GIT_TAG=$(aws ssm get-parameter --name /app/qa/$APPLICATION_NAME/RELEASE_ID | jq -r ".Parameter.Value")
      - export IMAGE_TAG="${GIT_TAG:-latest}"
  post_build:
    commands:
      - envsubst < taskdef.json > out && mv out taskdef.json
      - envsubst < appspec.yaml > out && mv out appspec.yaml
artifacts:
  files:
    - taskdef.json
    - appspec.yaml
